language: php

sudo: false

php:
	- 7.1

install:
	- composer self-update
	- composer install --prefer-source

script:
	- composer test

after_script:
	- wget https://scrutinizer-ci.com/ocular.phar
	- php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

matrix:
	fast_finish: true
